import numpy as np

from pandas._typing import Dtype

def is_nested_object(obj) -> bool: ...
def infer_dtype_from(val, pandas_dtype: bool = ...): ...
def infer_dtype_from_scalar(val, pandas_dtype: bool = ...): ...
def infer_dtype_from_array(arr, pandas_dtype: bool = ...): ...
def invalidate_string_dtypes(dtype_set) -> None: ...
def coerce_indexer_dtype(indexer, categories): ...
def astype_nansafe(arr, dtype, copy: bool = ..., skipna: bool = ...): ...
def soft_convert_objects(
    values: np.ndarray,
    datetime: bool = ...,
    numeric: bool = ...,
    timedelta: bool = ...,
    coerce: bool = ...,
    copy: bool = ...,
): ...
def convert_dtypes(
    input_array,
    convert_string: bool = ...,
    convert_integer: bool = ...,
    convert_boolean: bool = ...,
) -> Dtype: ...
def find_common_type(types): ...
def construct_1d_arraylike_from_scalar(value, length: int, dtype): ...
def construct_1d_object_array_from_listlike(values): ...
