def create_pandas_abc_type(name, attr, comp): ...

class ABCIndex: ...
class ABCInt64Index: ...
class ABCUInt64Index: ...
class ABCRangeIndex: ...
class ABCFloat64Index: ...
class ABCMultiIndex: ...
class ABCDatetimeIndex: ...
class ABCTimedeltaIndex: ...
class ABCCategoricalIndex: ...
class ABCIntervalIndex: ...
class ABCSeries: ...
class ABCDataFrame: ...
class ABCCategorical: ...
class ABCDatetimeArray: ...
class ABCTimedeltaArray: ...
class ABCPeriod: ...
class ABCExtensionArray: ...
class ABCPandasArray: ...
