from collections.abc import Hashable
from numbers import Number
from typing import TypeGuard

import numpy as np

from pandas._libs import lib

is_bool = lib.is_bool
is_integer = lib.is_integer
is_float = lib.is_float
is_complex = lib.is_complex
is_scalar = lib.is_scalar
is_list_like = lib.is_list_like
is_iterator = lib.is_iterator

def is_number(obj: object) -> TypeGuard[Number | np.number]: ...
def is_file_like(obj: object) -> bool: ...
def is_re(obj: object) -> bool: ...
def is_re_compilable(obj: object) -> bool: ...
def is_array_like(obj: object) -> bool: ...
def is_nested_list_like(obj: object) -> bool: ...
def is_dict_like(obj: object) -> bool: ...
def is_named_tuple(obj: object) -> bool: ...
def is_hashable(obj: object, allow_slice: bool = True) -> TypeGuard[Hashable]: ...
def is_sequence(obj: object) -> bool: ...
def is_dataclass(obj: object) -> bool: ...
