import ast

from pandas.core.computation.scope import Scope as Scope

class BaseExprVisitor(ast.NodeVisitor):
    const_type = ...
    term_type = ...
    binary_ops = ...
    binary_op_nodes = ...
    binary_op_nodes_map = ...
    unary_ops = ...
    unary_op_nodes = ...
    unary_op_nodes_map = ...
    rewrite_map = ...
    env = ...
    engine = ...
    parser = ...
    preparser = ...
    assigner = ...

class Expr:
    env: Scope
    engine: str
    parser: str
    expr = ...
    terms = ...
