class Scope:
    level = ...
    scope = ...
    target = ...
    resolvers = ...
    temps = ...
    @property
    def has_resolvers(self) -> bool: ...
    @property
    def ntemps(self) -> int: ...
