# This file serves as a stub file for static type checkers
# (pyright does not like it if I call the file tests/_typing.pyi).
# In tests/conftest.py, this file is copied to tests/_typing.pyi, and
# pandas-stubs/_typing.pyi is copied to tests/_typing.py.
# After tests are done, tests/_typing.pyi is copied back to
# pandas-stubs/_typing.pyi.
# Do not commit this file if its content is identical to pandas-stubs/_typing.pyi.

from pandas._typing import (
    BooleanDtypeArg,
    BytesDtypeArg,
    CategoryDtypeArg,
    ComplexDtypeArg,
    FloatDtypeArg,
    IntDtypeArg,
    ObjectDtypeArg,
    PandasAstypeComplexDtypeArg,
    PandasAstypeFloatDtypeArg,
    PandasAstypeTimedeltaDtypeArg,
    PandasAstypeTimestampDtypeArg,
    PandasFloatDtypeArg,
    StrDtypeArg,
    TimedeltaDtypeArg,
    TimestampDtypeArg,
    UIntDtypeArg,
    VoidDtypeArg,
    np_1darray,
    np_1darray_anyint,
    np_1darray_bool,
    np_1darray_bytes,
    np_1darray_complex,
    np_1darray_dt,
    np_1darray_float,
    np_1darray_int64,
    np_1darray_intp,
    np_1darray_object,
    np_1darray_td,
    np_2darray,
    np_ndarray,
    np_ndarray_anyint,
    np_ndarray_bool,
    np_ndarray_complex,
    np_ndarray_dt,
    np_ndarray_float,
    np_ndarray_int64,
    np_ndarray_intp,
    np_ndarray_num,
    np_ndarray_str,
    np_ndarray_td,
)

__all__ = [
    "np_1darray",
    "np_2darray",
    "np_ndarray",
    "np_1darray_bool",
    "BooleanDtypeArg",
    "BytesDtypeArg",
    "CategoryDtypeArg",
    "ComplexDtypeArg",
    "IntDtypeArg",
    "np_ndarray_str",
    "ObjectDtypeArg",
    "PandasAstypeComplexDtypeArg",
    "PandasAstypeTimedeltaDtypeArg",
    "PandasAstypeTimestampDtypeArg",
    "StrDtypeArg",
    "TimedeltaDtypeArg",
    "TimestampDtypeArg",
    "UIntDtypeArg",
    "PandasFloatDtypeArg",
    "VoidDtypeArg",
    "np_1darray",
    "np_1darray_anyint",
    "np_1darray_bool",
    "np_1darray_bytes",
    "np_1darray_complex",
    "np_1darray_dt",
    "np_1darray_float",
    "np_ndarray_bool",
    "np_ndarray_dt",
    "np_1darray_object",
    "np_1darray_td",
    "np_1darray_int64",
    "np_ndarray_num",
    "FloatDtypeArg",
    "PandasAstypeFloatDtypeArg",
    "np_ndarray_bool",
    "np_ndarray_dt",
    "np_ndarray_td",
    "np_1darray_intp",
    "np_ndarray_anyint",
    "np_ndarray_complex",
    "np_ndarray_float",
    "np_ndarray_int64",
    "np_ndarray_intp",
]
