# This file is a type-checking shim for tests that need stub-only aliases.
#
# - Static type checkers (where TYPE_CHECKING is True) see the re-export from
#   pandas._typing, i.e. the stub package pandas-stubs/_typing.pyi.
# - At runtime, real pandas._typing lacks the stub-only array aliases, so the
#   definitions in pandas-stubs/_typing.pyi are executed in this module's
#   namespace instead.
# - The single source of truth is pandas-stubs/_typing.pyi; the import list
#   below must match the names used by the tests.

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pandas._typing import (
        BooleanDtypeArg,
        BuiltinBooleanDtypeArg,
        BuiltinBytesDtypeArg,
        BuiltinComplexDtypeArg,
        BuiltinFloatDtypeArg,
        BuiltinIntDtypeArg,
        BuiltinNotObjDtypeArg,
        BuiltinNotStrObjDtypeArg,
        BuiltinObjectDtypeArg,
        BuiltinStrDtypeArg,
        BytesDtypeArg,
        CategoryDtypeArg,
        ComplexDtypeArg,
        FloatDtypeArg,
        IntDtypeArg,
        NumpyBooleanDtypeArg,
        NumpyBytesDtypeArg,
        NumpyComplexDtypeArg,
        NumpyFloat16DtypeArg,
        NumpyFloatNot16DtypeArg,
        NumpyIntDtypeArg,
        NumpyNotTimeDtypeArg,
        NumpyObjectDtypeArg,
        NumpyStrDtypeArg,
        NumpyTimedeltaDtypeArg,
        NumpyTimestampDtypeArg,
        NumpyUIntDtypeArg,
        NumpyVoidDtypeArg,
        ObjectDtypeArg,
        PandasAstypeTimedeltaDtypeArg,
        PandasAstypeTimestampDtypeArg,
        PandasBaseStrDtypeArg,
        PandasBooleanDtypeArg,
        PandasFloatDtypeArg,
        PandasIntDtypeArg,
        PandasStrDtypeArg,
        PandasTimestampDtypeArg,
        PandasUIntDtypeArg,
        PyArrowBooleanDtypeArg,
        PyArrowBytesDtypeArg,
        PyArrowFloatDtypeArg,
        PyArrowIntDtypeArg,
        PyArrowStrDtypeArg,
        PyArrowTimedeltaDtypeArg,
        PyArrowTimestampDtypeArg,
        PyArrowUIntDtypeArg,
        StrDtypeArg,
        TimedeltaDtypeArg,
        TimestampDtypeArg,
        TimeUnit,
        UIntDtypeArg,
        VoidDtypeArg,
        np_1darray,
        np_1darray_anyint,
        np_1darray_bool,
        np_1darray_bytes,
        np_1darray_complex,
        np_1darray_dt,
        np_1darray_float,
        np_1darray_int8,
        np_1darray_int32,
        np_1darray_int64,
        np_1darray_intp,
        np_1darray_object,
        np_1darray_str,
        np_1darray_td,
        np_2darray,
        np_ndarray,
        np_ndarray_anyint,
        np_ndarray_bool,
        np_ndarray_complex,
        np_ndarray_dt,
        np_ndarray_float,
        np_ndarray_int64,
        np_ndarray_intp,
        np_ndarray_num,
        np_ndarray_object,
        np_ndarray_str,
        np_ndarray_td,
    )

__all__ = [
    "BooleanDtypeArg",
    "BuiltinBooleanDtypeArg",
    "BuiltinBytesDtypeArg",
    "BuiltinComplexDtypeArg",
    "BuiltinFloatDtypeArg",
    "BuiltinIntDtypeArg",
    "BuiltinNotObjDtypeArg",
    "BuiltinNotStrObjDtypeArg",
    "BuiltinObjectDtypeArg",
    "BuiltinStrDtypeArg",
    "BytesDtypeArg",
    "CategoryDtypeArg",
    "ComplexDtypeArg",
    "FloatDtypeArg",
    "IntDtypeArg",
    "NumpyBooleanDtypeArg",
    "NumpyBytesDtypeArg",
    "NumpyComplexDtypeArg",
    "NumpyFloat16DtypeArg",
    "NumpyFloatNot16DtypeArg",
    "NumpyIntDtypeArg",
    "NumpyNotTimeDtypeArg",
    "NumpyObjectDtypeArg",
    "NumpyStrDtypeArg",
    "NumpyTimedeltaDtypeArg",
    "NumpyTimestampDtypeArg",
    "NumpyUIntDtypeArg",
    "NumpyVoidDtypeArg",
    "ObjectDtypeArg",
    "PandasAstypeTimedeltaDtypeArg",
    "PandasAstypeTimestampDtypeArg",
    "PandasBaseStrDtypeArg",
    "PandasBooleanDtypeArg",
    "PandasFloatDtypeArg",
    "PandasIntDtypeArg",
    "PandasStrDtypeArg",
    "PandasTimestampDtypeArg",
    "PandasUIntDtypeArg",
    "PyArrowBooleanDtypeArg",
    "PyArrowBytesDtypeArg",
    "PyArrowFloatDtypeArg",
    "PyArrowIntDtypeArg",
    "PyArrowStrDtypeArg",
    "PyArrowTimedeltaDtypeArg",
    "PyArrowTimestampDtypeArg",
    "PyArrowUIntDtypeArg",
    "StrDtypeArg",
    "TimeUnit",
    "TimedeltaDtypeArg",
    "TimestampDtypeArg",
    "UIntDtypeArg",
    "VoidDtypeArg",
    "np_1darray",
    "np_1darray_anyint",
    "np_1darray_bool",
    "np_1darray_bytes",
    "np_1darray_complex",
    "np_1darray_dt",
    "np_1darray_float",
    "np_1darray_int8",
    "np_1darray_int32",
    "np_1darray_int64",
    "np_1darray_intp",
    "np_1darray_object",
    "np_1darray_str",
    "np_1darray_td",
    "np_2darray",
    "np_ndarray",
    "np_ndarray_anyint",
    "np_ndarray_bool",
    "np_ndarray_complex",
    "np_ndarray_dt",
    "np_ndarray_float",
    "np_ndarray_int64",
    "np_ndarray_intp",
    "np_ndarray_num",
    "np_ndarray_object",
    "np_ndarray_str",
    "np_ndarray_td",
]

if not TYPE_CHECKING:
    from pathlib import Path

    _source = Path(__file__).parents[1] / "pandas-stubs" / "_typing.pyi"
    exec(compile(_source.read_text(), str(_source), "exec"), globals())  # noqa: S102
