def hash_pandas_object(
    obj,
    index: bool = ...,
    encoding: str = ...,
    hash_key: str | None = ...,
    categorize: bool = ...,
): ...
def hash_tuples(vals, encoding=..., hash_key: str = ...): ...
def hash_tuple(val, encoding: str = ..., hash_key: str = ...): ...
def hash_array(
    vals, encoding: str = ..., hash_key: str = ..., categorize: bool = ...
): ...
