# TODO: Remove PyperclipException after switch to 1.5.x, moved to pandas.errors
class PyperclipException(RuntimeError): ...

class PyperclipWindowsException(PyperclipException):
    def __init__(self, message) -> None: ...
