from datetime import tzinfo as _tzinfo

import numpy as np
import numpy.typing as npt
from pandas.core.arrays.datetimelike import (
    DatelikeOps,
    DatetimeLikeArrayMixin,
    TimelikeOps,
)
from pandas.core.arrays.period import PeriodArray
from pandas.core.indexes.base import Index
from pandas.core.series import Series
from typing_extensions import Self

from pandas._libs.tslibs.period import Period
from pandas._typing import (
    DtypeArg,
    Frequency,
    TimeAmbiguous,
    TimeNonexistent,
    TimeZones,
)

from pandas.core.dtypes.dtypes import DatetimeTZDtype as DatetimeTZDtype

class DatetimeArray(DatetimeLikeArrayMixin, TimelikeOps, DatelikeOps):
    __array_priority__: int = ...
    def __init__(
        self,
        values: Series | Index | DatetimeArray | npt.NDArray[np.object_],
        dtype: DtypeArg | None = None,
        freq: Frequency | None = None,
        copy: bool = False,
    ) -> None: ...
    # ignore in dtype() is from the pandas source
    @property
    def dtype(self) -> np.dtype | DatetimeTZDtype: ...  # type: ignore[override] # pyright: ignore[reportIncompatibleMethodOverride]
    @property
    def tzinfo(self) -> _tzinfo | None: ...
    @property
    def is_normalized(self) -> bool: ...
    def tz_convert(self, tz: TimeZones) -> Self: ...
    def tz_localize(
        self,
        tz: TimeZones,
        ambiguous: TimeAmbiguous = "raise",
        nonexistent: TimeNonexistent = "raise",
    ) -> Self: ...
    def to_pydatetime(self) -> npt.NDArray[np.object_]: ...
    def normalize(self) -> Self: ...
    def to_period(self, freq: str | Period | None = None) -> PeriodArray: ...
    def month_name(self, locale: str | None = None) -> Series | Index: ...
    def day_name(self, locale: str | None = None) -> Series | Index: ...
    @property
    def time(self) -> npt.NDArray[np.object_]: ...
    @property
    def timetz(self) -> npt.NDArray[np.object_]: ...
    @property
    def date(self) -> npt.NDArray[np.object_]: ...
    year = ...
    month = ...
    day = ...
    hour = ...
    minute = ...
    second = ...
    microsecond = ...
    nanosecond = ...
    dayofweek = ...
    weekday = ...
    dayofyear = ...
    quarter = ...
    days_in_month = ...
    daysinmonth = ...
    is_month_start = ...
    is_month_end = ...
    is_quarter_start = ...
    is_quarter_end = ...
    is_year_start = ...
    is_year_end = ...
    is_leap_year = ...
    def to_julian_date(self) -> npt.NDArray[np.float64]: ...
