from collections.abc import Iterator
from datetime import tzinfo as _tzinfo
import sys
from typing import Any

import numpy as np
from pandas.core.arrays.datetimelike import (
    DatelikeOps,
    DatetimeLikeArrayMixin,
    TimelikeOps,
)
from pandas.core.arrays.period import PeriodArray
from pandas.core.indexes.base import Index
from pandas.core.series import Series
from typing_extensions import Self

from pandas._libs.tslibs.timestamps import Timestamp
from pandas._typing import (
    DtypeArg,
    Frequency,
    TimeAmbiguous,
    TimeNonexistent,
    TimeZones,
    np_1darray,
    np_1darray_float,
    np_1darray_object,
    np_ndarray,
)

from pandas.core.dtypes.dtypes import DatetimeTZDtype as DatetimeTZDtype

class DatetimeArray(DatetimeLikeArrayMixin, TimelikeOps, DatelikeOps):
    __array_priority__: int = ...
    def __init__(
        self,
        values: Series | Index | DatetimeArray | np_ndarray,
        dtype: DtypeArg | None = None,
        freq: Frequency | None = None,
        copy: bool = False,
    ) -> None: ...
    # ignore in dtype() is from the pandas source
    if sys.version_info >= (3, 11):
        @property
        def dtype(self) -> np.dtype | DatetimeTZDtype: ...  # type: ignore[override] # pyright: ignore[reportIncompatibleMethodOverride]
    else:
        @property
        def dtype(self) -> np.dtype[Any] | DatetimeTZDtype: ...  # type: ignore[override] # pyright: ignore[reportIncompatibleMethodOverride] # pyrefly: ignore[bad-override]

    @property
    def tz(self) -> _tzinfo | None: ...
    @property
    def tzinfo(self) -> _tzinfo | None: ...
    @property
    def is_normalized(self) -> bool: ...
    def __iter__(self) -> Iterator[Timestamp]: ...
    def tz_convert(self, tz: TimeZones) -> Self: ...
    def tz_localize(
        self,
        tz: TimeZones,
        ambiguous: TimeAmbiguous = "raise",
        nonexistent: TimeNonexistent = "raise",
    ) -> Self: ...
    def to_pydatetime(self) -> np_1darray_object: ...
    def normalize(self) -> Self: ...
    def to_period(self, freq: Frequency | None = None) -> PeriodArray: ...
    # TODO: BaseStringArray after Pandas 3.0 pandas-dev/pandas#57064
    def month_name(self, locale: str | None = None) -> np_ndarray: ...
    # TODO: BaseStringArray after Pandas 3.0 pandas-dev/pandas#57064
    def day_name(self, locale: str | None = None) -> np_ndarray: ...
    @property
    def time(self) -> np_1darray: ...
    @property
    def timetz(self) -> np_1darray: ...
    @property
    def date(self) -> np_1darray: ...
    year = ...
    month = ...
    day = ...
    hour = ...
    minute = ...
    second = ...
    microsecond = ...
    nanosecond = ...
    dayofweek = ...
    weekday = ...
    dayofyear = ...
    quarter = ...
    days_in_month = ...
    daysinmonth = ...
    is_month_start = ...
    is_month_end = ...
    is_quarter_start = ...
    is_quarter_end = ...
    is_year_start = ...
    is_year_end = ...
    is_leap_year = ...
    def to_julian_date(self) -> np_1darray_float: ...
