from pandas.core.arrays.masked import BaseMaskedArray

from pandas._libs.missing import NAType
from pandas._typing import (
    AnyArrayLike,
    np_ndarray_bool,
)

from pandas.core.dtypes.base import ExtensionDtype as ExtensionDtype

class _IntegerDtype(ExtensionDtype):
    base: None
    @property
    def na_value(self) -> NAType: ...
    @property
    def itemsize(self) -> int: ...
    @classmethod
    def construct_array_type(cls) -> type[IntegerArray]: ...

class IntegerArray(BaseMaskedArray):
    @property
    def dtype(self) -> _IntegerDtype: ...
    def __init__(
        self,
        values: AnyArrayLike,
        mask: np_ndarray_bool,
        copy: bool = False,
    ) -> None: ...

class Int8Dtype(_IntegerDtype): ...
class Int16Dtype(_IntegerDtype): ...
class Int32Dtype(_IntegerDtype): ...
class Int64Dtype(_IntegerDtype): ...
class UInt8Dtype(_IntegerDtype): ...
class UInt16Dtype(_IntegerDtype): ...
class UInt32Dtype(_IntegerDtype): ...
class UInt64Dtype(_IntegerDtype): ...
