from typing import Any

from pandas import PeriodDtype
from pandas.core.arrays.datetimelike import (
    DatelikeOps,
    DatetimeLikeArrayMixin,
)
from pandas.core.arrays.datetimes import DatetimeArray
from pandas.core.indexes.period import PeriodIndex
from pandas.core.series import Series
import pyarrow as pa

from pandas._libs.tslibs.period import Period
from pandas._typing import (
    DtypeArg,
    NpDtype,
    PeriodFrequency,
    np_1darray,
    np_1darray_anyint,
    np_1darray_bool,
    np_ndarray_anyint,
)

class PeriodArray(DatetimeLikeArrayMixin, DatelikeOps):
    __array_priority__: int = ...
    def __init__(
        self,
        values: np_ndarray_anyint | PeriodArray | PeriodIndex | Series[Period],
        dtype: PeriodDtype | None = None,
        copy: bool = False,
    ) -> None: ...
    @property
    def dtype(self) -> PeriodDtype: ...
    def __array__(
        self, dtype: NpDtype | None = None, copy: bool | None = None
    ) -> np_1darray: ...
    def __arrow_array__(
        self, type: DtypeArg | None = None
    ) -> pa.ExtensionArray[Any]: ...
    year: np_1darray_anyint = ...
    month: np_1darray_anyint = ...
    day: np_1darray_anyint = ...
    hour: np_1darray_anyint = ...
    minute: np_1darray_anyint = ...
    second: np_1darray_anyint = ...
    weekofyear: np_1darray_anyint = ...
    week: np_1darray_anyint = ...
    dayofweek: np_1darray_anyint = ...
    weekday: np_1darray_anyint = ...
    dayofyear: np_1darray_anyint = ...
    day_of_year: np_1darray_anyint = ...
    quarter: np_1darray_anyint = ...
    qyear: np_1darray_anyint = ...
    days_in_month: np_1darray_anyint = ...
    daysinmonth: np_1darray_anyint = ...
    @property
    def is_leap_year(self) -> np_1darray_bool: ...
    @property
    def start_time(self) -> DatetimeArray: ...
    @property
    def end_time(self) -> DatetimeArray: ...
    def to_timestamp(
        self, freq: PeriodFrequency | None = None, how: str = ...
    ) -> DatetimeArray: ...
    def asfreq(self, freq: str | None = ..., how: str = "E") -> PeriodArray: ...
