from pandas.core.indexes.base import Index

def inherit_names(names: list[str], delegate, cache: bool = ..., wrap: bool = ...): ...

class ExtensionIndex(Index):
    def __getitem__(self, key): ...
    def __iter__(self): ...
    def dropna(self, how: str = ...): ...
    def repeat(self, repeats, axis=...): ...
    def take(
        self, indices, axis: int = ..., allow_fill: bool = ..., fill_value=..., **kwargs
    ): ...
    def unique(self, level=...): ...
    def map(self, mapper, na_action=...): ...
    def astype(self, dtype, copy: bool = ...): ...
