from __future__ import annotations

from pandas._typing import FilePathOrBuffer

gcsfs = ...

def get_filepath_or_buffer(
    filepath_or_buffer: FilePathOrBuffer, encoding=..., compression=..., mode=...
): ...
