"""Generate the checked-in architecture documents from the versioned snapshot."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[2]
DATA = ROOT / "docs" / "architecture" / "data"


def read_jsonl(path: Path) -> list[dict[str, object]]:
    return [
        json.loads(line)
        for line in path.read_text(encoding="utf-8").splitlines()
        if line
    ]


def outputs(root: Path) -> dict[Path, str]:
    manifest = json.loads((DATA / "manifest.json").read_text(encoding="utf-8"))
    prs = {
        record["number"]: record for record in read_jsonl(DATA / "pull_requests.jsonl")
    }
    clusters = json.loads((DATA / "semantic_clusters.json").read_text(encoding="utf-8"))
    result: dict[Path, str] = {}
    chronicle_links: list[str] = []
    for cluster in clusters:
        filename = cluster["filename"]
        records = [prs[number] for number in cluster["pull_requests"]]
        lines = [
            f"# {cluster['title']}",
            "",
            "<!-- Generated by scripts.architecture; do not edit. -->",
            "",
            (
                "This chronicle is derived only from the committed architecture snapshot. "
                f"It is valid for base commit pandas-dev/pandas-stubs@{manifest['base_commit_short']}."
            ),
            "",
            "## Historical PR index",
            "",
            "| PR | Merged | Merge commit |",
            "| :--- | :--- | :--- |",
        ]
        lines.extend(
            f"| pandas-dev/pandas-stubs#{record['number']} | {record['merged_at']} | "
            f"pandas-dev/pandas-stubs@{record['merge_commit'][:7]} |"
            for record in records
        )
        lines.extend(["", "## Scope", "", f"{cluster['summary']}", ""])
        target = root / "docs" / "architecture" / "generated" / "chronicles" / filename
        result[target] = "\n".join(lines)
        chronicle_links.append(
            f"- [{cluster['title']}](generated/chronicles/{filename})"
        )

    result[root / "docs" / "architecture" / "README.md"] = "\n".join(
        [
            "# pandas-stubs Architecture Knowledge Base",
            "",
            "<!-- Generated by scripts.architecture; do not edit. -->",
            "",
            (
                "The generated architecture record is reproducible from the committed tools and "
                "snapshot data. It is a historical record valid for "
                f"pandas-dev/pandas-stubs@{manifest['base_commit_short']}, not a claim about later commits."
            ),
            "",
            "## Provenance",
            "",
            f"- Collected: {manifest['collected_at']}",
            f"- Base commit: pandas-dev/pandas-stubs@{manifest['base_commit_short']}",
            (
                f"- Snapshot records: {manifest['record_counts']['pull_requests']} merged PRs, "
                f"{manifest['record_counts']['issues']} issues, and {manifest['record_counts']['commits']} merge commits."
            ),
            "- Generation: `python scripts/architecture/generate.py generate`",
            "- Validation: `python scripts/architecture/check.py`",
            "",
            "## Generated chronicles",
            "",
            *chronicle_links,
            "",
            "## Hand-maintained references",
            "",
            "- [Architecture decisions](decisions/)",
            "- [Subsystem guides](subsystems/)",
            "- [Type matrices](matrices/)",
            "- [Type architecture](concepts/type-architecture.md)",
            "",
        ]
    )
    return result


def write_outputs(root: Path) -> None:
    for path, content in outputs(root).items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def check() -> bool:
    with tempfile.TemporaryDirectory() as directory:
        expected_root = Path(directory)
        write_outputs(expected_root)
        expected = outputs(expected_root)
        actual_paths = set(
            (ROOT / "docs" / "architecture" / "generated").glob("**/*.md")
        )
        expected_paths = {ROOT / path.relative_to(expected_root) for path in expected}
        ok = actual_paths == {
            path for path in expected_paths if "generated" in path.parts
        }
        for expected_path, content in expected.items():
            actual_path = ROOT / expected_path.relative_to(expected_root)
            if (
                not actual_path.exists()
                or actual_path.read_text(encoding="utf-8") != content
            ):
                sys.stdout.write(
                    f"architecture output drift: {actual_path.relative_to(ROOT)}\n"
                )
                ok = False
        if not ok:
            sys.stdout.write("Run: python scripts/architecture/generate.py generate\n")
        return ok


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=("generate", "check"))
    args = parser.parse_args()
    if args.command == "generate":
        write_outputs(ROOT)
    elif not check():
        raise SystemExit(1)


if __name__ == "__main__":
    main()
