from collections.abc import Collection
from datetime import (
    date,
    datetime,
    time,
    timedelta,
)
from typing import (
    Any,
    Literal,
    Self,
    TypeVar,
    overload,
)

from dateutil.relativedelta import weekday as WeekdayClass
import numpy as np
from typing_extensions import override

from pandas._libs.tslibs.nattype import NaTType
from pandas._libs.tslibs.timedeltas import Timedelta
from pandas._libs.tslibs.timestamps import Timestamp
from pandas._typing import (
    Frequency,
    Just,
    ShapeT,
    np_ndarray_object,
)

from pandas.tseries.holiday import AbstractHolidayCalendar

_DatetimeT = TypeVar("_DatetimeT", bound=datetime)
_TimedeltaT = TypeVar("_TimedeltaT", bound=timedelta)

class ApplyTypeError(TypeError): ...

class BaseOffset:
    n: int
    def __init__(self, n: int = ..., normalize: bool = ...) -> None: ...
    @override
    def __eq__(self, other: object, /) -> bool: ...
    @override
    def __ne__(self, other: object, /) -> bool: ...
    @override
    def __hash__(self) -> int: ...
    @property
    def kwds(self) -> dict[str, Any]: ...
    @property
    def base(self) -> BaseOffset: ...
    # Adding an offset to a datetime-like value yields a `Timestamp` (`NaT` propagates),
    # and object arrays are applied elementwise.  Every offset supports this, but the
    # delta offsets accept durations and their own family as well, so they widen these
    # overloads; the offsets that only shift to an anchor reject durations and other
    # offsets at runtime.  mypy forbids widening the operand domain of a forward
    # operator override, so each widened `__add__` carries `type: ignore[override]`.
    @overload
    def __add__(
        self, other: np_ndarray_object[ShapeT], /
    ) -> np_ndarray_object[ShapeT]: ...
    @overload
    def __add__(self, other: NaTType, /) -> NaTType: ...
    @overload
    def __add__(self, other: date | np.datetime64, /) -> Timestamp: ...
    @overload
    def __radd__(
        self, other: np_ndarray_object[ShapeT], /
    ) -> np_ndarray_object[ShapeT]: ...
    @overload
    def __radd__(self, other: NaTType, /) -> NaTType: ...
    @overload
    def __radd__(self, other: date | np.datetime64, /) -> Timestamp: ...
    def __sub__(self, other: BaseOffset, /) -> Self: ...
    @overload
    def __rsub__(
        self, other: np_ndarray_object[ShapeT], /
    ) -> np_ndarray_object[ShapeT]: ...
    @overload
    def __rsub__(self, other: _DatetimeT, /) -> _DatetimeT: ...  # type: ignore[overload-overlap] # pyright: ignore[reportOverlappingOverload]
    @overload
    def __rsub__(self, other: date, /) -> Timestamp: ...
    @overload
    def __rsub__(self, other: BaseOffset, /) -> Self: ...
    @overload
    def __rsub__(self, other: _TimedeltaT, /) -> _TimedeltaT: ...
    @overload
    def __mul__(
        self, other: np_ndarray_object[ShapeT], /
    ) -> np_ndarray_object[ShapeT]: ...
    @overload
    def __mul__(self, other: int, /) -> Self: ...
    @overload
    def __rmul__(
        self, other: np_ndarray_object[ShapeT], /
    ) -> np_ndarray_object[ShapeT]: ...
    @overload
    def __rmul__(self, other: int, /) -> Self: ...
    def __neg__(self) -> Self: ...
    def copy(self) -> Self: ...
    @property
    def name(self) -> str: ...
    @property
    def rule_code(self) -> str: ...
    @property
    def freqstr(self) -> str: ...
    def rollback(self, dt: datetime | Timestamp) -> Timestamp: ...
    def rollforward(self, dt: datetime | Timestamp) -> Timestamp: ...
    def is_on_offset(self, dt: datetime) -> bool: ...
    @property
    def nanos(self) -> int: ...

class SingleConstructorOffset(BaseOffset): ...

@overload
def to_offset(freq: None, is_period: bool = False) -> None: ...
@overload
def to_offset(freq: Frequency | timedelta, is_period: bool = False) -> BaseOffset: ...

class Tick(SingleConstructorOffset):
    def __init__(self, n: int = ..., normalize: bool = ...) -> None: ...
    @property
    @override
    def nanos(self) -> int: ...
    # Adding two ticks of the same concrete class preserves that class; mixing them
    # normalizes to the coarsest non-zero unit, which cannot be expressed statically,
    # so the exact-class overloads come first and `Tick` covers the remainder.
    @overload  # type: ignore[override]
    @override
    def __add__(
        self, other: np_ndarray_object[ShapeT], /
    ) -> np_ndarray_object[ShapeT]: ...
    @overload
    def __add__(self, other: NaTType, /) -> NaTType: ...
    @overload
    def __add__(self, other: date | np.datetime64, /) -> Timestamp: ...
    @overload
    def __add__(self: Just[Hour], other: Just[Hour], /) -> Hour: ...
    @overload
    def __add__(self: Just[Minute], other: Just[Minute], /) -> Minute: ...
    @overload
    def __add__(self: Just[Second], other: Just[Second], /) -> Second: ...
    @overload
    def __add__(self: Just[Milli], other: Just[Milli], /) -> Milli: ...
    @overload
    def __add__(self: Just[Micro], other: Just[Micro], /) -> Micro: ...
    @overload
    def __add__(self: Just[Nano], other: Just[Nano], /) -> Nano: ...
    @overload
    def __add__(self, other: Tick, /) -> Tick: ...
    @overload
    def __add__(self, other: Day | Week, /) -> Timedelta: ...
    @overload
    def __add__(
        self, other: timedelta | np.timedelta64 | Timedelta, /
    ) -> Timedelta: ...
    @overload
    def __add__(self, other: BusinessDay, /) -> BusinessDay: ...
    @overload
    @override
    def __radd__(
        self, other: np_ndarray_object[ShapeT], /
    ) -> np_ndarray_object[ShapeT]: ...
    @overload
    def __radd__(self, other: NaTType, /) -> NaTType: ...
    @overload
    def __radd__(self, other: date | np.datetime64, /) -> Timestamp: ...
    @overload
    def __radd__(self: Just[Hour], other: Just[Hour], /) -> Hour: ...
    @overload
    def __radd__(self: Just[Minute], other: Just[Minute], /) -> Minute: ...
    @overload
    def __radd__(self: Just[Second], other: Just[Second], /) -> Second: ...
    @overload
    def __radd__(self: Just[Milli], other: Just[Milli], /) -> Milli: ...
    @overload
    def __radd__(self: Just[Micro], other: Just[Micro], /) -> Micro: ...
    @overload
    def __radd__(self: Just[Nano], other: Just[Nano], /) -> Nano: ...
    @overload
    def __radd__(self, other: Tick, /) -> Tick: ...
    # Unlike `__add__`, the reflected method leaves day-or-finer offsets to their own
    # `__add__` and returns `NotImplemented`, so only durations are declared here.
    @overload
    def __radd__(
        self, other: timedelta | np.timedelta64 | Timedelta, /
    ) -> Timedelta: ...

class Day(SingleConstructorOffset):
    # Adding a duration to `Day` preserves that duration's own type, while a sub-day
    # tick collapses to a `Timedelta` and `Week` degenerates to a plain `timedelta`.
    @overload  # type: ignore[override]
    @override
    def __add__(
        self, other: np_ndarray_object[ShapeT], /
    ) -> np_ndarray_object[ShapeT]: ...
    @overload
    def __add__(self, other: NaTType, /) -> NaTType: ...
    @overload
    def __add__(self, other: date | np.datetime64, /) -> Timestamp: ...
    @overload
    def __add__(self, other: Day, /) -> Day: ...
    @overload
    def __add__(self, other: Tick, /) -> Timedelta: ...
    @overload
    def __add__(self, other: Week, /) -> timedelta: ...
    @overload
    def __add__(self, other: np.timedelta64, /) -> np.timedelta64: ...
    @overload
    def __add__(self, other: _TimedeltaT, /) -> _TimedeltaT: ...
    @overload
    def __add__(self, other: BusinessDay, /) -> BusinessDay: ...
    @overload
    @override
    def __radd__(
        self, other: np_ndarray_object[ShapeT], /
    ) -> np_ndarray_object[ShapeT]: ...
    @overload
    def __radd__(self, other: NaTType, /) -> NaTType: ...
    @overload
    def __radd__(self, other: date | np.datetime64, /) -> Timestamp: ...
    @overload
    def __radd__(self, other: Day, /) -> Day: ...
    @overload
    def __radd__(self, other: Tick, /) -> Timedelta: ...
    @overload
    def __radd__(self, other: Week, /) -> timedelta: ...
    @overload
    def __radd__(self, other: np.timedelta64, /) -> np.timedelta64: ...
    @overload
    def __radd__(self, other: _TimedeltaT, /) -> _TimedeltaT: ...
    @overload
    def __radd__(self, other: BusinessDay, /) -> BusinessDay: ...

class Hour(Tick): ...
class Minute(Tick): ...
class Second(Tick): ...
class Milli(Tick): ...
class Micro(Tick): ...
class Nano(Tick): ...

class RelativeDeltaOffset(BaseOffset):
    def __init__(self, n: int = ..., normalize: bool = ..., **kwds: Any) -> None: ...

# Changed from implementation because it is not allowed for `PeriodDtype`
class BusinessDay(BaseOffset):
    def __init__(
        self, n: int = ..., normalize: bool = ..., offset: timedelta = ...
    ) -> None: ...
    # A duration or a day-or-finer offset folds into `offset=`, so the result is a
    # plain `BusinessDay` even for `CustomBusinessDay` receivers.
    @overload  # type: ignore[override]
    @override
    def __add__(
        self, other: np_ndarray_object[ShapeT], /
    ) -> np_ndarray_object[ShapeT]: ...
    @overload
    def __add__(self, other: NaTType, /) -> NaTType: ...
    @overload
    def __add__(self, other: date | np.datetime64, /) -> Timestamp: ...
    @overload
    def __add__(
        self, other: timedelta | np.timedelta64 | Day | Tick | Week, /
    ) -> BusinessDay: ...
    @overload
    @override
    def __radd__(
        self, other: np_ndarray_object[ShapeT], /
    ) -> np_ndarray_object[ShapeT]: ...
    @overload
    def __radd__(self, other: NaTType, /) -> NaTType: ...
    @overload
    def __radd__(self, other: date | np.datetime64, /) -> Timestamp: ...
    # As with `Tick`, day-or-coarser offsets are handled by their own `__add__`.
    @overload
    def __radd__(self, other: timedelta | np.timedelta64 | Tick, /) -> BusinessDay: ...

class BusinessHour(SingleConstructorOffset):
    def __init__(
        self,
        n: int = ...,
        normalize: bool = ...,
        start: str | time | Collection[str | time] = ...,
        end: str | time | Collection[str | time] = ...,
        offset: timedelta = ...,
    ) -> None: ...

class WeekOfMonthMixin(SingleConstructorOffset):
    def __init__(
        self, n: int = ..., weekday: Literal[0, 1, 2, 3, 4, 5, 6] = ...
    ) -> None: ...

class YearOffset(SingleConstructorOffset):
    def __init__(
        self, n: int = ..., normalize: bool = ..., month: int | None = ...
    ) -> None: ...

class BYearEnd(YearOffset): ...
class BYearBegin(YearOffset): ...
class YearEnd(YearOffset): ...
class YearBegin(YearOffset): ...

class QuarterOffset(SingleConstructorOffset):
    def __init__(
        self, n: int = ..., normalize: bool = ..., startingMonth: int | None = ...
    ) -> None: ...

class BQuarterEnd(QuarterOffset): ...
class BQuarterBegin(QuarterOffset): ...
class QuarterEnd(QuarterOffset): ...
class QuarterBegin(QuarterOffset): ...

class HalfYearOffset(SingleConstructorOffset):
    def __init__(
        self, n: int = 1, normalize: bool = False, startingMonth: int | None = False
    ) -> None: ...

class BHalfYearEnd(HalfYearOffset): ...
class BHalfYearBegin(HalfYearOffset): ...
class HalfYearEnd(HalfYearOffset): ...
class HalfYearBegin(HalfYearOffset): ...
class MonthOffset(SingleConstructorOffset): ...
class MonthEnd(MonthOffset): ...
class MonthBegin(MonthOffset): ...
class BusinessMonthEnd(MonthOffset): ...
class BusinessMonthBegin(MonthOffset): ...

class SemiMonthOffset(SingleConstructorOffset):
    def __init__(
        self, n: int = ..., normalize: bool = ..., day_of_month: int | None = ...
    ) -> None: ...

class SemiMonthEnd(SemiMonthOffset): ...
class SemiMonthBegin(SemiMonthOffset): ...

class Week(SingleConstructorOffset):
    def __init__(
        self, n: int = ..., normalize: bool = ..., weekday: int | None = ...
    ) -> None: ...
    @overload  # type: ignore[override]
    @override
    def __add__(
        self, other: np_ndarray_object[ShapeT], /
    ) -> np_ndarray_object[ShapeT]: ...
    @overload
    def __add__(self, other: NaTType, /) -> NaTType: ...
    @overload
    def __add__(self, other: date | np.datetime64, /) -> Timestamp: ...
    @overload
    def __add__(self, other: Tick, /) -> Timedelta: ...
    @overload
    def __add__(self, other: Day | Week, /) -> timedelta: ...
    @overload
    def __add__(self, other: np.timedelta64, /) -> timedelta: ...
    @overload
    def __add__(self, other: _TimedeltaT, /) -> _TimedeltaT: ...
    @overload
    def __add__(self, other: BusinessDay, /) -> BusinessDay: ...
    @overload
    @override
    def __radd__(
        self, other: np_ndarray_object[ShapeT], /
    ) -> np_ndarray_object[ShapeT]: ...
    @overload
    def __radd__(self, other: NaTType, /) -> NaTType: ...
    @overload
    def __radd__(self, other: date | np.datetime64, /) -> Timestamp: ...
    @overload
    def __radd__(self, other: Tick, /) -> Timedelta: ...
    @overload
    def __radd__(self, other: Day | Week, /) -> timedelta: ...
    @overload
    def __radd__(self, other: np.timedelta64, /) -> timedelta: ...
    @overload
    def __radd__(self, other: _TimedeltaT, /) -> _TimedeltaT: ...
    @overload
    def __radd__(self, other: BusinessDay, /) -> BusinessDay: ...

class WeekOfMonth(WeekOfMonthMixin):
    def __init__(
        self, n: int = ..., normalize: bool = ..., week: int = ..., weekday: int = ...
    ) -> None: ...

class LastWeekOfMonth(WeekOfMonthMixin): ...

class FY5253Mixin(SingleConstructorOffset):
    def __init__(
        self,
        n: int = ...,
        normalize: bool = ...,
        weekday: int = ...,
        startingMonth: int = ...,
        variation: str = ...,
    ) -> None: ...

class FY5253(FY5253Mixin): ...
class FY5253Quarter(FY5253Mixin): ...

class Easter(SingleConstructorOffset):
    def __init__(
        self,
        n: int = 1,
        normalize: bool = False,
        method: int = ...,
    ) -> None: ...

class _CustomBusinessMonth(SingleConstructorOffset):
    def __init__(
        self,
        n: int = ...,
        normalize: bool = ...,
        weekmask: str = ...,
        holidays: list[Any] | None = ...,
        calendar: AbstractHolidayCalendar | np.busdaycalendar | None = ...,
        offset: timedelta = ...,
    ) -> None: ...

class CustomBusinessDay(BusinessDay):
    def __init__(
        self,
        n: int = ...,
        normalize: bool = ...,
        weekmask: str = ...,
        holidays: list[Any] | None = ...,
        calendar: AbstractHolidayCalendar | np.busdaycalendar | None = ...,
        offset: timedelta = ...,
    ) -> None: ...
    @property
    def weekmask(self) -> str: ...
    @property
    def holidays(self) -> tuple[np.datetime64, ...]: ...
    @property
    def calendar(self) -> np.busdaycalendar: ...

class CustomBusinessHour(BusinessHour):
    def __init__(
        self,
        n: int = ...,
        normalize: bool = ...,
        start: str | time | Collection[str | time] = ...,
        end: str | time | Collection[str | time] = ...,
        offset: timedelta = ...,
        holidays: list[Any] | None = ...,
    ) -> None: ...

class CustomBusinessMonthEnd(_CustomBusinessMonth): ...
class CustomBusinessMonthBegin(_CustomBusinessMonth): ...

class DateOffset(RelativeDeltaOffset):
    def __init__(
        self,
        *,
        n: int = ...,
        normalize: bool = ...,
        years: int = ...,
        months: int = ...,
        weeks: int = ...,
        days: int = ...,
        hours: int = ...,
        minutes: int = ...,
        seconds: int = ...,
        milliseconds: int = ...,
        microseconds: int = ...,
        nanoseconds: int = ...,
        year: int = ...,
        month: int = ...,
        day: int = ...,
        weekday: int | WeekdayClass = ...,
        hour: int = ...,
        minute: int = ...,
        second: int = ...,
        microsecond: int = ...,
        nanosecond: int = ...,
    ) -> None: ...

BDay = BusinessDay
BMonthEnd = BusinessMonthEnd
BMonthBegin = BusinessMonthBegin
CBMonthEnd = CustomBusinessMonthEnd
CBMonthBegin = CustomBusinessMonthBegin
CDay = CustomBusinessDay
