from typing import Any

class DateParseError(ValueError):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

def guess_datetime_format(dt_str: str, dayfirst: bool = False) -> str | None: ...
