import pandas as pd

from pandas.io.sas.sasreader import SASReader

class XportReader(SASReader):
    def close(self) -> None: ...
    def __next__(self) -> pd.DataFrame: ...
    def read(self, nrows: int | None = None) -> pd.DataFrame: ...
