from pandas._config.config import OptionError as OptionError

from pandas._libs.tslibs import (
    OutOfBoundsDatetime as OutOfBoundsDatetime,
    OutOfBoundsTimedelta as OutOfBoundsTimedelta,
)

from pandas.io.clipboard import PyperclipWindowsException as PyperclipWindowsException

# TODO: Uncomment import below after switch to 1.5.x.
# from pandas.core.computation.ops import UndefinedVariableError as UndefinedVariableError

class IntCastingNaNError(ValueError): ...
class NullFrequencyError(ValueError): ...
class PerformanceWarning(Warning): ...
class UnsupportedFunctionCall(ValueError): ...
class UnsortedIndexError(KeyError): ...
class ParserError(ValueError): ...
class DtypeWarning(Warning): ...
class EmptyDataError(ValueError): ...
class ParserWarning(Warning): ...
class MergeError(ValueError): ...
class AccessorRegistrationWarning(Warning): ...

class AbstractMethodError(NotImplementedError):
    def __init__(self, class_instance, methodtype: str = ...) -> None: ...

class NumbaUtilError(Exception): ...
class DuplicateLabelError(ValueError): ...
class InvalidIndexError(Exception): ...

# TODO: Uncomment and delete from pandas.core.base after switch to 1.5.x
# class DataError(Exception): ...
# class SpecificationError(Exception): ...
# TODO: Uncomment and delete from pandas.core.common after switch to 1.5.x
# class SettingWithCopyError(ValueError): ...
# class SettingWithCopyWarning(Warning): ...
# TODO: Uncomment and delete from pandas.core.computation.engines after switch to 1.5.x
# class NumExprClobberingError(NameError): ...
# TODO: Uncomment and delete from core.indexing after switch to 1.5.x
# class IndexingError(Exception): ...
# TODO: Uncomment and delete from io.clipboards.__init__ after switch to 1.5.x
# class PyperclipException(RuntimeError): ...
# TODO: Uncomment and delete from io.formats.css after switch to 1.5.x
# class CSSWarning(UserWarning): ...
# TODO: Uncomment and delete next 4 from io.pytables after switch to 1.5.x
# class PossibleDataLossError(Exception): ...
# class ClosedFileError(Exception): ...
# class IncompatibilityWarning(Warning): ...
# class AttributeConflictWarning(Warning): ...
# TODO: Uncomment and delete from io.sql after switch to 1.5.x
# class DatabaseError(OSError): ...
# TODO: Uncomment and delete from io.stata after switch to 1.5.x
# class PossiblePrecisionLoss(Warning): ...
# class ValueLabelTypeMismatch(Warning): ...
# class InvalidColumnName(Warning): ...
# class CategoricalConversionWarning(Warning): ...
