from collections.abc import Sequence
from typing import Any

import numpy as np
from typing_extensions import Self

from pandas._typing import (
    AnyArrayLikeInt,
    AxisInt,
    DtypeObj,
    Shape,
)

class NDArrayBacked:
    _dtype: DtypeObj
    _ndarray: np.ndarray
    def __setstate__(self, state: Any) -> None: ...
    def __len__(self) -> int: ...
    @property
    def shape(self) -> Shape: ...
    @property
    def ndim(self) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def nbytes(self) -> int: ...
    def copy(self, order=...) -> Self: ...
    def delete(self, loc, axis=...) -> Self: ...
    def swapaxes(self, axis1, axis2) -> Self: ...
    def repeat(
        self,
        repeats: int | Sequence[int] | AnyArrayLikeInt,
        axis: AxisInt | None = None,
    ) -> Self: ...
    def reshape(self, *args: Any, **kwargs: Any) -> Self: ...
    def ravel(self, order=...) -> Self: ...
    @property
    def T(self) -> Self: ...
