name: 'Optional'

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  pyrefly_all:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v7

    - name: Install project dependencies
      uses: ./.github/setup
      with:
        os: ubuntu-latest
        python-version: '3.14'

    - name: Run pyrefly tests with preset 'all'
      run: poetry run poe pyrefly_all

  ty_all:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v7

    - name: Install project dependencies
      uses: ./.github/setup
      with:
        os: ubuntu-latest
        python-version: '3.14'

    - name: Run ty tests with all rules raising errors
      run: poetry run poe ty_all
