name: 'Optional'

on:
  push:
    branches:
      - main
  workflow_dispatch:
  issue_comment:
    types:
      - created
      - edited

jobs:
  nightly:
    if: ${{ github.event_name != 'issue_comment' || ( github.event.issue.pull_request && contains(github.event.comment.body, '/pandas_nightly') ) }}

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3

    - name: Install project dependencies
      uses: ./.github/setup
      with:
        os: ubuntu-latest
        python-version: '3.11'

    - name: Run pytest (against pandas nightly)
      run: poetry run poe pytest --nightly

  mypy_nightly:
    if: ${{ github.event_name != 'issue_comment' || ( github.event.issue.pull_request && contains(github.event.comment.body, '/mypy_nightly') ) }}

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3

    - name: Install project dependencies
      uses: ./.github/setup
      with:
        os: ubuntu-latest
        python-version: '3.11'

    - name: Run mypy tests with mypy nightly
      run: poetry run poe mypy --mypy_nightly
