name: 'Optional'

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  nightly:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      actions: write

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        persist-credentials: false

    - name: Install project dependencies
      uses: ./.github/setup
      with:
        os: ubuntu-latest
        python-version: '3.11'

    - name: Run pytest (against pandas nightly)
      run: poetry run poe pytest --nightly

  mypy_nightly:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      actions: write

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        persist-credentials: false

    - name: Install project dependencies
      uses: ./.github/setup
      with:
        os: ubuntu-latest
        python-version: '3.11'

    - name: Run mypy tests with mypy nightly
      run: poetry run poe mypy --mypy_nightly
