name: 'Optional'

on:
  [push, workflow_dispatch]


jobs:
  nightly:
    if: ${{ github.repository == 'pandas-dev/pandas-stubs' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3

    - name: Install project dependencies
      uses: ./.github/setup
      with:
        os: ubuntu-latest
        python-version: '3.10'

    - name: Run pytest (against pandas nightly)
      run: poetry run poe pytest --nightly

  mypy_nightly:
    if: ${{ github.repository == 'pandas-dev/pandas-stubs' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3

    - name: Install project dependencies
      uses: ./.github/setup
      with:
        os: ubuntu-latest
        python-version: '3.10'

    - name: Run mypy tests with mypy nightly
      run: poetry run poe mypy --mypy_nightly
